/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadCvRouteImport } from './routes/upload-cv'
import { Route as SelectFieldRouteImport } from './routes/select-field'
import { Route as SelectCompanyRouteImport } from './routes/select-company'
import { Route as ReportRouteImport } from './routes/report'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const UploadCvRoute = UploadCvRouteImport.update({
  id: '/upload-cv',
  path: '/upload-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectFieldRoute = SelectFieldRouteImport.update({
  id: '/select-field',
  path: '/select-field',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectCompanyRoute = SelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/interview': typeof InterviewRoute
  '/report': typeof ReportRoute
  '/select-company': typeof SelectCompanyRoute
  '/select-field': typeof SelectFieldRoute
  '/upload-cv': typeof UploadCvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/interview': typeof InterviewRoute
  '/report': typeof ReportRoute
  '/select-company': typeof SelectCompanyRoute
  '/select-field': typeof SelectFieldRoute
  '/upload-cv': typeof UploadCvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/interview': typeof InterviewRoute
  '/report': typeof ReportRoute
  '/select-company': typeof SelectCompanyRoute
  '/select-field': typeof SelectFieldRoute
  '/upload-cv': typeof UploadCvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/interview'
    | '/report'
    | '/select-company'
    | '/select-field'
    | '/upload-cv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/interview'
    | '/report'
    | '/select-company'
    | '/select-field'
    | '/upload-cv'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home'
    | '/interview'
    | '/report'
    | '/select-company'
    | '/select-field'
    | '/upload-cv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  InterviewRoute: typeof InterviewRoute
  ReportRoute: typeof ReportRoute
  SelectCompanyRoute: typeof SelectCompanyRoute
  SelectFieldRoute: typeof SelectFieldRoute
  UploadCvRoute: typeof UploadCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-cv': {
      id: '/upload-cv'
      path: '/upload-cv'
      fullPath: '/upload-cv'
      preLoaderRoute: typeof UploadCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-field': {
      id: '/select-field'
      path: '/select-field'
      fullPath: '/select-field'
      preLoaderRoute: typeof SelectFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-company': {
      id: '/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof SelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  InterviewRoute: InterviewRoute,
  ReportRoute: ReportRoute,
  SelectCompanyRoute: SelectCompanyRoute,
  SelectFieldRoute: SelectFieldRoute,
  UploadCvRoute: UploadCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
